- school: KTH Royal Institute of Technology
  degree: Masters in Machine Learning
  period: Sep 2024 - Present
  desc: "Subjects: Intro to ML & AI, Advanced ML, GPU Programming, Building Network Security, ANN & Deep Learning Architectures, Speech Recognition."

- school: KTH Royal Institute of Technology
  degree: Exchange Student
  period: Sep 2023 - Jan 2024
  desc: "Subjects: Ethical Hacking, Cybersecurity Overview, Compiler Construction, Distributed AI & Intelligent Agents."

- school: Technische Universiteit Delft
  degree: Honours Degree
  period: Sep 2022 - Aug 2024
  desc: "Research in program synthesis algorithms. Contributed to the Herb program synthesis framework."

- school: Technische Universiteit Delft
  degree: Bachelor in Computer Science and Engineering
  period: Sep 2021 - July 2024
  desc: "Main Subjects: Software Project, ML, Algorithms & Data Structures, Databases, Web Development, OS, Networks. Learned Java Spring Boot and team collaboration."

- school: Tudor Vianu National High School
  degree: High School Diploma
  period: Sep 2017 - July 2021
  desc: "Informatics (Intensive), Mathematics, Physics. Participated in competitive programming and Romanian Olympiad in Informatics."
